# Site settings
name: 武林秀才的技术博客
email: zhongdh@hnswdx.gov.cn
author: zhongdh
#url: http://9506.website
resume_site: #http://www.hifreud.com/Resume.io/
github: https://github.com/yueyue2007/
baseurl: ""
description: Actually, less is more!
meta_description: 个人技术博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: #It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: yueyue2007
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
